
[2017-12-18 10:03:58] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 228, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 93, in main
    print_s(head_soup)
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 68, in print_s
    callers_local_vars = inspect.currentframe().f_back.f_locals.items()
NameError: name 'inspect' is not defined


[2017-12-18 10:04:32] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 228, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 93, in main
    print_s(head_soup)
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 68, in print_s
    callers_local_vars = inspect.currentframe().f_back.f_locals.items()
NameError: name 'inspect' is not defined


[2017-12-18 11:17:52] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 247, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 103, in main
    th_soup.insert_after(th_tag)
AttributeError: 'list' object has no attribute 'insert_after'


[2017-12-18 11:20:06] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 247, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 103, in main
    th_soup[-1].insert_after(th_tag)
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 416, in insert_after
    parent.insert(index+1, successor)
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 312, in insert
    raise ValueError("Cannot insert None into a tag.")
ValueError: Cannot insert None into a tag.


[2017-12-18 11:22:01] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 248, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 104, in main
    th_soup[len(th_tag)-1].insert_after(th_tag)
TypeError: object of type 'NoneType' has no len()


[2017-12-18 11:23:17] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 248, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 104, in main
    th_soup[len(th_tag)-1].insert_after(th_tag)
TypeError: object of type 'NoneType' has no len()


[2017-12-18 11:25:12] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 249, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 113, in main
    build.insert_after(td_tag)
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 416, in insert_after
    parent.insert(index+1, successor)
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 312, in insert
    raise ValueError("Cannot insert None into a tag.")
ValueError: Cannot insert None into a tag.


[2017-12-18 11:27:17] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 250, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 114, in main
    build.insert_after(td_tag)
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 416, in insert_after
    parent.insert(index+1, successor)
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 312, in insert
    raise ValueError("Cannot insert None into a tag.")
ValueError: Cannot insert None into a tag.


[2017-12-18 11:28:09] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 252, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 118, in main
    browser = cef.CreateBrowserSync(url=html_to_data_uri(HTML_code),
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 143, in html_to_data_uri
    html = html.encode("utf-8", "replace")
AttributeError: 'function' object has no attribute 'encode'


[2017-12-18 11:35:39] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 252, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 105, in main
    print_s(th_soup[-1]).insert_after(th_tag)
AttributeError: 'NoneType' object has no attribute 'insert_after'


[2017-12-18 13:59:57] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 192, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 42, in main
    set_global_handler()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 146, in set_global_handler
    global_handler = GlobalHandler()
NameError: name 'GlobalHandler' is not defined


[2017-12-18 14:02:58] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 177, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 42, in main
    set_global_handler()
NameError: name 'set_global_handler' is not defined


[2017-12-18 14:03:34] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 176, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 60, in main
    button.inser(0, 'Update!')
TypeError: 'NoneType' object is not callable


[2017-12-18 17:00:31] Traceback (most recent call last):
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 98, in <module>
    main()
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\gui.py", line 47, in main
    builds = Builds()
TypeError: __init__() should return None, not 'Builds'


[2017-12-18 17:01:53] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py36.V8FunctionHandler_Execute (cefpython_py36.cpp:97829)
  File "C:\Users\Thomas\Documents\GitHub\pickit-cl\lib\gui_html.py", line 153, in update
    'input[type="checkbox", selected="True"]')
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 1355, in select
    candidates = self.select(partial_selector, limit=limit)
  File "D:\Dateien\Programme\Anaconda\lib\site-packages\bs4\element.py", line 1477, in select
    'Unsupported or invalid CSS selector: "%s"' % token)
ValueError: Unsupported or invalid CSS selector: "input[type=checkbox"

